title: nextWorld
author: DreamApart
email: pastever@gmail.com
disqusShortname: nextWorld

auto: true
pygments: true
lsi: false

markdown: rdiscount
pygments: true

permalink: /:categories/:year-:month-:day/:title
paginate: 10
exclude:
  [".rvmrc", ".rbenv-version", "README.md", "Rakefile",
  "changelog.md"]
