title: nerd's laboratory
author: dycforever
email: dycforever@126.com
disqusShortname: nerd's laboratory

auto: true
pygments: true
lsi: false

markdown: rdiscount
pygments: true

permalink: /:categories/:year-:month-:day/:title
paginate: 10
exclude:
  [".rvmrc", ".rbenv-version", "README.md", "Rakefile",
  "changelog.md"]
